import React from 'react'
import styles from './page.module.css'
import Button from '@/app/components/button/Button'
import Image from 'next/image'
import vm from '/public/vitalitymg.jpeg'
import {items} from '../[projects]/data'
import {notFound} from 'next/navigation'

const getData=() => {
    const data = items.projects
   
if (data){
    return data
} 
return notFound()   
}

export const metadata = {
  title: 'Proyectos',
  description: 'Generated by create next app',
}

function Projects({params}) {
    const data = getData(params.projects)

  return (
    <div className={styles.container}>

      {data.map((item) => (
            <div className={styles.item} key = {item.id}>
               <div className={styles.content}>

              <h1 className={styles.title}>{item.title}</h1>
              <p className={styles.description}>{item.description}</p>
              <Button text= 'MAS' 
              url = {item.url}/>
              </div> 
              <div className={styles.imgContainer}>
                 
                 <Image 
                    src={item.image} 
                    alt="img"
                    className={styles.img} 
                 />

              </div>
            </div>
      ))}

    </div>
  )
}

export default Projects
