import React from 'react'
import styles from './page.module.css'
import Image from 'next/image'
import Button from '../components/button/Button'
import img from '/public/agile-ilustration.webp'

export const metadata = {
  title: 'Sobre mi',
  description: 'Generated by create next app',
}

function About() {
  return (
  <div className={styles.container}>
     
    <div className={styles.imgContainer}>
     
     <Image src={img}  
            alt="img" 
            className={styles.img} 
      />

        <div className={styles.imgText}>
          <h1 className={styles.imgTitle}>Siempre en movimiento</h1>
        </div>
    </div>

    <div className={styles.textContainer}>
      
      <div className={styles.item}>
        <h1>QUIEN SOY?</h1>
          <p> Nacida y criada en Buenos Aires, soy una persona curiosa y determinada.
            Desde siempre me gustaron los desafíos y encontrar formas creativas para atravesarlos. <br /> <br />
            Soy música improvisadora y fotógrafa. Me encanta aprender nuevos lenguajes, disfruto de investigar diferentes formas de expresarme.
            De alguna manera esa búsqueda me hizo llegar a la programación, otro nuevo lenguaje en mi vida.
           <br /> <br />
           Estudié en Henry la carrera de Fullstack Developer, y aunque no fue facil, logré sumergirme en el mundo de la tecnologia con mucho entusiasmo.
          Lo que mas me apasiona es el Front-end porque me parece fascinante ver el codigo trasformado en algo que todxs pueden ver.
          <br /><br />  Quiero seguir adentrandome en este mundo, se que puede seguir expandiendo mi creatividad.
            </p>
      </div>
          <div className={styles.item}>
            <h1>ESTUDIOS</h1>
            <p> 🔖 Henry Bootcamp <br /> <br />
            Bootcamp Fullstack Developer aprendi diferentes lenguajes y tecnologias como Javascript, HTML/CSS, React, Redux, Express, Node.js, Material UI, Next.js</p>
            
            <p> 🔖 Gender Mainstreaming Workshop : <br /> <br />
            Curso diseñado para ayudar a reconocer y combatir los prejuicios de género que influyen en el trabajo y vida personal
            
              <br />  
              </p>

              <Button url="/contact" text="CONTACT"></Button>
          </div>
    </div>
  </div>
  ) 
}

export default About

  