'use client'
import React from 'react'
import { useRef } from 'react'
import styles from './page.module.css'
import Image from 'next/image'
import img from '/public/contact-illustration.gif'
import { Button } from '@mui/material'
import emailjs from "@emailjs/browser"

// export const metadata = {
//   title: 'Hablemos!',
//   description: 'Generated by create next app',
// }

function Contact() {

  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm('service_4dno4lr', 'template_qvs4g9k', form.current, 'AEdqHymH08sXI592v')
      .then((result) => {
          console.log("ok");
      }, (error) => {
          console.log(error.text);
      });
  };

  return (
    <div className={styles.container}>
      <h1 className={styles.title}>HABLEMOS!</h1>
      <div className={styles.content}>

        <div className={styles.imgContainer}>
          <Image src={img} alt='' className={styles.img}/>
        </div>
      
       <form className={styles.form} ref={form} onSubmit={sendEmail} >

        <input 
        type="text" 
        name= 'user_name'
        minLength={3}
        maxLength={150}
        placeholder='nombre' 
        className={styles.input} 
        required />

        <input type="email" 
        name= 'user_email'
        placeholder='email'
        minLength={5}
        maxLength={150} 
        className={styles.input} 
        required />
        
        <textarea 
        placeholder='mensaje' 
        name = "message"
        cols='30' rows='10' className={styles.textArea}
        required></textarea> 

        <Button variant="outlined" type = 'submit' value='Send'> ENVIAR!</Button>
       </form>
      </div>
    </div>
      // </div>
    // </div>
  )
}

export default Contact
