import React from 'react'
import styles from './page.module.css'
import Link from 'next/link'
import app from '/public/appIcon.png'
import vg from '/public/723d0af616b1fe7d5c7e56a3532be3cd.jpg'
import Image from 'next/image'

export const metadata = {
  title: 'Proyectos',
  description: 'Generated by create next app',
}

function Portfolio() {

  return (
    <div className={styles.container} >
      <div className={styles.items}>
        <Link href="/portfolio/apps" rel='preload' className={styles.item}>
          <div>
          <Image src={app}  
            alt="img" 
            className={styles.img} 
      />
          </div>
        <span className={styles.subTitle}>Apps</span>
        </Link>
        {/* <Link href="/portfolio/videogames" rel='preload' className={styles.item}>
        <div>
          <Image src={vg}  
            alt="img" 
            className={styles.img} 
      />
          </div>
        <span className={styles.subTitle}> Videogames</span>
        </Link> */}

      </div>


    </div>
  )
}

export default Portfolio
