// este archivo corre los componentes. Aca se ve todo lo que se va a ver
// en toda la pagina como el navbar y el footer 
import './globals.css'
import Navbar from './components/navbar/Navbar.jsx'
import Footer from './components/footer/Footer.jsx'
import { Lexend_Peta } from 'next/font/google'
import { ThemeProvider } from '../context/ThemeContext'


const inter = Lexend_Peta({ subsets: ['latin'] })

export const metadata = {
  title: 'Catu Hardoy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body className={inter.className}>
        
        <ThemeProvider>
            <div className='container'>
            <Navbar/>
            {children}
            <Footer/>
            </div>
        </ThemeProvider>
       
      
      </body>
    
        
    </html>
  )
}
